services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\CouponCommandBundle\Service\:
    resource: '../../Service/'

  Tourze\CouponCommandBundle\Repository\:
    resource: '../../Repository/'

  Tourze\CouponCommandBundle\Controller\:
    resource: '../../Controller/'

  Tourze\CouponCommandBundle\Procedure\:
    resource: '../../Procedure/'

